### ISSUE TITLE
Update push deployment scripts

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.bob.web#111]
The push deployment scripts have been updated: https://github.com/4teamwork/plone-git-deployment/commits/master
The copies in the templates are outdated.

Should we update them here or should we change the mechanism to update on template build?

**Comment by elioschmutz** [comment]
@jone Whats about executing always the script directly from github:

Folder structure:

- my.package
  - deploy
    - after_push (contains: `curl -s https://raw.githubusercontent.com/4teamwork/plone-git-deployment/master/deploy/after_push | bash -s`)
    - notify_errbit (contains: `curl -s https://raw.githubusercontent.com/4teamwork/plone-git-deployment/master/deploy/notify_errbit | bash -s`)
    - ...

are there some disadvantages? Whats about the security? Or do you have another suggestion?

**Comment by jone** [comment]
@elioschmutz yes, that would be best, I think.
It would be awesome if this was done during package creation, so that we always have the newest version.
Be aware that `notify_errbit` is no longer recommended, see the [setup script](https://github.com/4teamwork/plone-git-deployment/blob/master/setup).
