### ISSUE TITLE
ContentManager Rolle erstellen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.bob.web#18]
- footer
- portlets

Actiongroup: manage content settings

**Comment by maethu** [comment]
Meiner Meinung nach gehört dies zum "Site Administrator" und benötigt keine zusätzliche Rolle. 
Ist bei...:
- Zug
- Bern
- Winterthur
- Basel

... so.

**Comment by elioschmutz** [comment]
Wie sieht es nun hier aus? Weiterfahren mit "Site Administrator" oder neue Rolle "Content Manager" erstellen?

**Comment by elioschmutz** [comment]
@maethu @jone

**Comment by jone** [comment]
Finde `Site Administrator` ok.
Für site root muss es übrigens noch ins `rolemap.xml`.

**Comment by maethu** [comment]
👍

**Comment by elioschmutz** [comment]
Die Permissions werden bereits in den jeweiligen Modulen im `rolemap.xml` dem `Site Administrator` zugewiesen:

Portlets
- https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/default/rolemap.xml#L170

Footer
- https://github.com/4teamwork/ftw.footer/blob/master/ftw/footer/profiles/default/rolemap.xml#L6
