### ISSUE TITLE
UserManager rolle erstellen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.bob.web#19]
Siehe https://github.com/4teamwork/kapozh.workspace/commit/8a5b582c5a2e0936d93d4191efaf965195498764

**Comment by jone** [comment]
Obacht: die `User Manager` Rolle sollte m.E. ins `ftw.usermanagement` :arrow_right: 4teamwork/ftw.usermanagement#28

**Comment by elioschmutz** [comment]
Wurde in https://github.com/4teamwork/ftw.usermanagement/issues/28 umgesetzt.
