### ISSUE TITLE
Maintenance-Page: remove logo and colors

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.bob.web#20]
1) The generated maintenance page has a transparent 4teamwork **logo**, white text on white background, the text is not readable.
I'd prefer not having a logo at all by default, so that the maintenance-page can be used for any project without the need to replace the logo. The easiest way is to just not have a logo :wink: 

2) The page currently has a **green border**. The green may not be appropriate for e.g. a red-ish page.
In order to not have this problem I'd propose to not use a color and just use a greyscale page.

This is not urgent.
Maybe @bierik can make a nice looking maintenance page sometime? :wink:

**Comment by jone** [comment]
@bierik : the maintenance-page at https://github.com/4teamwork/ftw.bob.web/blob/master/ftw/bob/web/template/%2Bpackage.fullname%2B/maintenance/index.html should be improved 😉 
This is low prio.

**Comment by elioschmutz** [comment]
@raphael-s Bitte Punkt 1 und 2 umsetzten.

@bierik wird in einem weiteren Schritt die Maintenance-Seite überarbeiten: #40
