### ISSUE TITLE
git-deploy not completely set up

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.bob.web#21]
git-deploy requires a `log` and a `tmp` directory.
We usually symlink `log` to `var/log` and create an ignored `tmp` directory.
See the [setup script](https://github.com/4teamwork/plone-git-deployment/blob/master/setup#L42-L45) or the [readme](https://github.com/4teamwork/plone-git-deployment#add-deployment-scripts-to-repository).

**Comment by elioschmutz** [comment]
How should I do this?

The directory `var/log` is not available at the beginning and I cannot make a symlink to an unexisting directory.

**Comment by jone** [comment]
`ln` does not require the target to exist. You can just do a `ln -s var/log` even when there is no var directory.

**Comment by maethu** [comment]
push
