### ISSUE TITLE
Anmelde-Action per Default deaktivieren

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.bob.web#31]
Der Anmelde-Knopf soll per Default in Websites nicht angezeigt werden.

Dazu muss die Action in `portal_actions` => `user` deaktiviert werden.

Siehe als Beispiel für die Umsetzung: https://github.com/4teamwork/ses.web/blob/master/ses/web/profiles/default/actions.xml

**Comment by jone** [comment]
Bin mir nicht sicher ob wir das Standardmässig ausblenden wollen oder ob dies jeweils im Projekte entschieden werden muss. @maethu was denkst du?

**Comment by elioschmutz** [comment]
Das ftw.bob.web Päckli erstellt ja Policies für Websites. Und Websites benötigen normalerweise keine Anmeldebutton.

Bisher benötigte kein Projekt, bei welchem die Seite mit ftw.bob erstellt wurde, den Anmeldebutton.
Und bei den Seiten, bei welchen der Anmeldebutton noch aktiviert ist, wurde dies nicht explizit entschieden sondern der Button war halt einfach da und man hat es so gelassen...

**Comment by jone** [comment]
Wenn ich als Redaktor an der Website arbeiten muss, wie gehe ich da vor?
(Beispiel-Installation ohne LDAP- / AD-Anbindung sowie ohne SSO).

Wenn ich z.B. Publisher einsetzen würde, würde ich den Butten auf der Redaktion einblenden, aber nicht auf WWW.

**Comment by elioschmutz** [comment]
Wir könnten den Anmeldelink z.B. im Footerportlet anzeigen lassen.

Grundsätzlich ist es ja so, dass Seiten mit Publisher oder AD-Anbindung grösser und aufwändiger sind als so normale Websites. Deshalb wäre es doch einfacher, den Standard für normale Seiten zu setzten und für grössere Projekte die Ausnahme.

**Comment by jone** [comment]
Ich sehe den Sinn nicht ganz, diesen Link in den Footer zu verschieben. Er ist ja dann immer noch sichtbar!?

Wie melden sich denn die Benutzer bei den Projekten an, bei denen du den Link ganz ausgeblendet hast?

**Comment by maethu** [comment]
> Das ftw.bob.web Päckli erstellt ja Policies für Websites. Und Websites benötigen normalerweise keine Anmeldebutton.

Aus meiner Sicht soll der Link by default angezeigt werden, damit der Benutzer weiss wie anmelden. 

Natürlich haben wir da auch andere Setups (Publisher), bei denen der Link nicht nötig ist. 
Aus meiner Sicht ist aber das Plone default Verhalten OK. 

Aus meiner Sicht wurde hier bereits zu viel diskutiert 😅  @elioschmutz falls du der Meinung bist, dass es raus muss, dann schmeiss es raus. Für mich ist der Aufwand zum Einblenden und Ausblenden gleich. 

Das Design zeigt die Benutzer-Aktionen oben rechts an, den Link in den Footer verschieben ist keine Option. Falls der Link oben rechts stört müssen wir das mit Kevin anschauen.

**Comment by elioschmutz** [comment]
😄  ja das stimmt... wollte eigentlich keine Diskussion anstiften...

@jone wir können das sonst am Montag noch kurz (5 min) zusammen besprechen... ist gut?

**Comment by raphael-s** [comment]
Wie ist hier der Stand? Habt ihr ( @elioschmutz @jone ) besprochen wie der Standard sein sollte?

**Comment by jone** [comment]
Nein, wir haben das noch nicht besprochen. Daher würde ich noch abwarten.

**Comment by elioschmutz** [comment]
Gem. Besprechung mit @jone soll der Anmeldeknopf standardmässig angezeigt.

In vielen Situationen wird der Anmeldeknopf benötigt.
Auch für einfache Websites wird von Kunden oft der "Anmeldeknopf" explizit gewünscht.
Zudem ist auch für den Aufbau einer Seite ein Anmeldeknopf von Vorteil.
