### ISSUE TITLE
ftw.lawgiver aktualisieren

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.bob.web#36]
Mit neuester ftw.lawgiver Version kompatibel machen.

Die Zeile `A Verwalter can always view inactive objects.` wird nicht mehr unterstützt und sollte grundsätzlich in keinem Workflow verwendet werden, siehe https://github.com/4teamwork/ftw.lawgiver/issues/27

Bitte Prüfen ob alle definierten Aktionsgruppen korrekt in der Spez verwendet werden.

**Comment by elioschmutz** [comment]
Alle Aktionsgruppen werden korrekt verwendet.
