### ISSUE TITLE
ftw.sliderblock in WEB aufnehmen.

### ISSUE THREAD

**Issue by maethu** [4teamwork/ftw.bob.web#71]
Zu beachten gilt hier, dass die SliderImages im Sliderblock keinen Workflow haben dürfen. 
ftw.slider setzt aber den default Workflow

**Comment by raphael-s** [comment]
SliderImages no longer have any workflow when installed via ftw.sliderblock: https://github.com/4teamwork/ftw.sliderblock/pull/24

**Comment by elioschmutz** [comment]
Closed by https://github.com/4teamwork/bobtemplates.4teamwork/issues/102
