### ISSUE TITLE
Not installed package gets "installed" in the test setup

### ISSUE THREAD

**Issue by shylux** [4teamwork/ftw.bob.web#79]
`ftw.simplelayout` is not installed in the module template. It is however used in the `testing.py`:
https://github.com/4teamwork/bobtemplates.4teamwork/blob/master/bobtemplates/module/%2Bpackage.fullname%2B/%2Bpackage.part_1%2B/%2Bpackage.part_2%2B/testing.py.bob#L24

**Comment by maethu** [comment]
Please remove this line. 
This line is only used in packaged with zcml registered `initialize` method.

For example Archetypes is using this method to register permissions in a generic way.
