### ISSUE TITLE
Remove redirect to workspaces

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/ftw.bob.web#89]
On a new installation, the site tries to redirect to `workspaces`, but it doesn't work, because `workspaces` doesn't exist.
The first thing the site should display is the dashboard.

https://github.com/4teamwork/bobtemplates.4teamwork/blob/master/bobtemplates/workspace/+package.fullname+/+package.part_1+/+package.part_2+/profiles/default/properties.xml#L8

![bildschirmfoto 2016-08-02 um 17 34 43](https://cloud.githubusercontent.com/assets/16755391/17334681/6d9d957e-58d7-11e6-856e-41459c0308db.png)

**Comment by maethu** [comment]
Wurde entfernt #92
